INFO:uvicorn.error:Started server process [16364]
INFO:uvicorn.error:Waiting for application startup.
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.Engine:[generated in 0.00015s] {}
INFO:sqlalchemy.engine.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Will watch for changes in these directories: ['C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [30592] using watchgod
INFO:uvicorn.error:Started server process [22540]
INFO:uvicorn.error:Waiting for application startup.
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.Engine:[generated in 0.00014s] {}
INFO:sqlalchemy.engine.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:uvicorn.error:Application startup complete.
WARNING:uvicorn.error:WatchGodReload detected file change in '['C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom\\service\\kiwoom.py']'. Reloading...
INFO:uvicorn.error:Started server process [932]
INFO:uvicorn.error:Waiting for application startup.
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.Engine:[generated in 0.00013s] {}
INFO:sqlalchemy.engine.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:uvicorn.error:Application startup complete.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\fastapi\routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\jinwoo\PycharmProjects\S05P21A602\backend\kiwoom\routers\stock.py", line 52, in get_last
    return k_win.getLastPrice(code=symbol)
TypeError: getLastPrice() got an unexpected keyword argument 'code'
WARNING:uvicorn.error:WatchGodReload detected file change in '['C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom\\routers\\stock.py']'. Reloading...
INFO:uvicorn.error:Started server process [29392]
INFO:uvicorn.error:Waiting for application startup.
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.Engine:[generated in 0.00020s] {}
INFO:sqlalchemy.engine.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:uvicorn.error:Application startup complete.
WARNING:uvicorn.error:WatchGodReload detected file change in '['C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom\\routers\\stock.py']'. Reloading...
INFO:uvicorn.error:Started server process [20736]
INFO:uvicorn.error:Waiting for application startup.
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.Engine:[generated in 0.00020s] {}
INFO:sqlalchemy.engine.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:uvicorn.error:Application startup complete.
WARNING:uvicorn.error:WatchGodReload detected file change in '['C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom\\service\\kiwoom.py']'. Reloading...
INFO:uvicorn.error:Started server process [11984]
INFO:uvicorn.error:Waiting for application startup.
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.Engine:[generated in 0.00013s] {}
INFO:sqlalchemy.engine.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Will watch for changes in these directories: ['C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [23520] using watchgod
INFO:uvicorn.error:Started server process [30612]
INFO:uvicorn.error:Waiting for application startup.
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.Engine:[generated in 0.00020s] {}
INFO:sqlalchemy.engine.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:uvicorn.error:Application startup complete.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\fastapi\routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\jinwoo\PycharmProjects\S05P21A602\backend\kiwoom\routers\stock.py", line 52, in get_last
    return k_win.getLastPrice(symbol=symbol)
  File "C:\Users\jinwoo\PycharmProjects\S05P21A602\backend\kiwoom\service\kiwoom.py", line 28, in getLastPrice
    df = Kiwoom().block_request("opt10001",
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\pykiwoom\kiwoom.py", line 24, in __init__
    self._set_signals_slots()
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\pykiwoom\kiwoom.py", line 87, in _set_signals_slots
    self.ocx.OnEventConnect.connect(self._handler_login)
AttributeError: 'QAxWidget' object has no attribute 'OnEventConnect'
WARNING:uvicorn.error:WatchGodReload detected file change in '['C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom\\routers\\stock.py']'. Reloading...
INFO:uvicorn.error:Started server process [10792]
INFO:uvicorn.error:Waiting for application startup.
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.Engine:[generated in 0.00020s] {}
INFO:sqlalchemy.engine.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:uvicorn.error:Application startup complete.
WARNING:uvicorn.error:WatchGodReload detected file change in '['C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom\\service\\kiwoom.py']'. Reloading...
INFO:uvicorn.error:Will watch for changes in these directories: ['C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [9880] using watchgod
INFO:uvicorn.error:Started server process [24176]
INFO:uvicorn.error:Waiting for application startup.
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.Engine:[generated in 0.00013s] {}
INFO:sqlalchemy.engine.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Will watch for changes in these directories: ['C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [29952] using watchgod
INFO:uvicorn.error:Started server process [21336]
INFO:uvicorn.error:Waiting for application startup.
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.Engine:[generated in 0.00020s] {}
INFO:sqlalchemy.engine.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:uvicorn.error:Application startup complete.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\fastapi\routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\jinwoo\PycharmProjects\S05P21A602\backend\kiwoom\routers\stock.py", line 54, in get_last
    return k_win.getLastPrice(symbol=symbol)
  File "C:\Users\jinwoo\PycharmProjects\S05P21A602\backend\kiwoom\service\kiwoom.py", line 29, in getLastPrice
    self.k = Kiwoom()
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\pykiwoom\kiwoom.py", line 24, in __init__
    self._set_signals_slots()
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\pykiwoom\kiwoom.py", line 87, in _set_signals_slots
    self.ocx.OnEventConnect.connect(self._handler_login)
AttributeError: 'QAxWidget' object has no attribute 'OnEventConnect'
WARNING:uvicorn.error:WatchGodReload detected file change in '['C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom\\routers\\stock.py', 'C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom\\service\\kiwoom.py']'. Reloading...
INFO:uvicorn.error:Will watch for changes in these directories: ['C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [9844] using watchgod
INFO:uvicorn.error:Started server process [17376]
INFO:uvicorn.error:Waiting for application startup.
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.Engine:[generated in 0.00020s] {}
INFO:sqlalchemy.engine.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:uvicorn.error:Application startup complete.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\fastapi\routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\jinwoo\PycharmProjects\S05P21A602\backend\kiwoom\routers\stock.py", line 52, in get_last
    k = Kiwoom()
NameError: name 'Kiwoom' is not defined
WARNING:uvicorn.error:WatchGodReload detected file change in '['C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom\\routers\\stock.py', 'C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom\\service\\kiwoom.py']'. Reloading...
INFO:uvicorn.error:Started server process [25756]
INFO:uvicorn.error:Waiting for application startup.
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.Engine:[generated in 0.00021s] {}
INFO:sqlalchemy.engine.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:uvicorn.error:Application startup complete.
INFO:uvicorn.error:Will watch for changes in these directories: ['C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [10448] using watchgod
INFO:uvicorn.error:Started server process [4928]
INFO:uvicorn.error:Waiting for application startup.
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.Engine:[generated in 0.00023s] {}
INFO:sqlalchemy.engine.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:uvicorn.error:Application startup complete.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\fastapi\routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\jinwoo\PycharmProjects\S05P21A602\backend\kiwoom\routers\stock.py", line 52, in get_last
    k = Kiwoom()
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\pykiwoom\kiwoom.py", line 24, in __init__
    self._set_signals_slots()
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\pykiwoom\kiwoom.py", line 87, in _set_signals_slots
    self.ocx.OnEventConnect.connect(self._handler_login)
AttributeError: 'QAxWidget' object has no attribute 'OnEventConnect'
WARNING:uvicorn.error:WatchGodReload detected file change in '['C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom\\routers\\stock.py']'. Reloading...
INFO:uvicorn.error:Started server process [11584]
INFO:uvicorn.error:Waiting for application startup.
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.Engine:[generated in 0.00021s] {}
INFO:sqlalchemy.engine.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:uvicorn.error:Application startup complete.
WARNING:uvicorn.error:WatchGodReload detected file change in '['C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom\\routers\\stock.py', 'C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom\\service\\kiwoom.py']'. Reloading...
INFO:uvicorn.error:Started server process [30656]
INFO:uvicorn.error:Waiting for application startup.
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.Engine:[generated in 0.00013s] {}
INFO:sqlalchemy.engine.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:uvicorn.error:Application startup complete.
ERROR:uvicorn.error:Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc from None
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\middleware\cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc from None
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\routing.py", line 52, in app
    response = await func(request)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\fastapi\routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\site-packages\starlette\concurrency.py", line 40, in run_in_threadpool
    return await loop.run_in_executor(None, func, *args)
  File "C:\Users\jinwoo\anaconda3\envs\py36_32_test\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\jinwoo\PycharmProjects\S05P21A602\backend\kiwoom\routers\stock.py", line 54, in get_last
    return k_win.getLastPrice(symbol=symbol, k=k)
NameError: name 'k' is not defined
WARNING:uvicorn.error:WatchGodReload detected file change in '['C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom\\service\\kiwoom.py']'. Reloading...
INFO:uvicorn.error:Started server process [23796]
INFO:uvicorn.error:Waiting for application startup.
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.Engine:[generated in 0.00013s] {}
INFO:sqlalchemy.engine.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:uvicorn.error:Application startup complete.
WARNING:uvicorn.error:WatchGodReload detected file change in '['C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom\\routers\\stock.py']'. Reloading...
INFO:uvicorn.error:Will watch for changes in these directories: ['C:\\Users\\jinwoo\\PycharmProjects\\S05P21A602\\backend\\kiwoom']
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:uvicorn.error:Started reloader process [5428] using watchgod
INFO:uvicorn.error:Started server process [14140]
INFO:uvicorn.error:Waiting for application startup.
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'sql_mode'
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:sqlalchemy.engine.Engine:SHOW VARIABLES LIKE 'lower_case_table_names'
INFO:sqlalchemy.engine.Engine:[generated in 0.00013s] {}
INFO:sqlalchemy.engine.Engine:SELECT DATABASE()
INFO:sqlalchemy.engine.Engine:[raw sql] {}
INFO:uvicorn.error:Application startup complete.
